version: '3.1'
services:
  react_set_db:
    image: mariadb:10.7.1-focal
    volumes:
      - reactdb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: reactdb
      MYSQL_ROOT_PASSWORD: battle
      MYSQL_USER: william
      MYSQL_PASSWORD: battle
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    ports:
      - 3366:3306

volumes:
  reactdb:
    driver: local
